events {
    worker_connections  1024;
}

http {
    upstream auth      { server host.docker.internal:3001; }
    upstream dispatch  { server host.docker.internal:3002; }
    upstream rtvs      { server host.docker.internal:3003; }
    upstream telelink  { server host.docker.internal:3004; }
    upstream epcr      { server host.docker.internal:3005; }
    upstream notify    { server host.docker.internal:3006; }
    upstream fleet     { server host.docker.internal:3007; }
    upstream hospital  { server host.docker.internal:3008; }
    upstream analytics { server host.docker.internal:3009; }
    upstream admin     { server host.docker.internal:3010; }

    server {
        listen 8080;

        location /v1/auth/      { proxy_pass http://auth; }
        location /v1/incidents/ { proxy_pass http://dispatch; }
        location /v1/rtvs/      { proxy_pass http://rtvs; }
        location /v1/telelink/  { proxy_pass http://telelink; }
        location /v1/epcr/      { proxy_pass http://epcr; }
        location /v1/vehicles/  { proxy_pass http://fleet; }
        location /v1/hospitals/ { proxy_pass http://hospital; }
        location /v1/analytics/ { proxy_pass http://analytics; }
        location /v1/admin/     { proxy_pass http://admin; }

        # WebSocket upgrade for RTVS live stream
        location /v1/rtvs/stream {
            proxy_pass http://rtvs;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}
